name: they don't think it be like it is
on: [push, pull_request]
jobs:
  it_do:
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: we/in/here/Gemfile
      RAKEFILE: we/in/here/Rakefile
    steps:
    - run: echo $BUNDLE_GEMFILE
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1 # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: rake -f "$RAKEFILE" db:reset
